MurrCard/urls.py
from django.urls import path

from MurrCard import views as murr_card

urlpatterns = [
    path('', murr_card.murr_list, name='murr_list'),
    path('like/', murr_card.like, name='like'),
    path('unlike/', murr_card.unlike, name='unlike'),
    path('by_tag/<str:tag_name>', murr_card.murr_list, name='murrs_by_tag_name'),
    path('by_category/<str:category>', murr_card.murr_list, name='murrs_by_category'),
    path('by_likes/<str:likes>', murr_card.murr_list, name='murrs_by_likes'),
    path('my/<str:my_murrs>', murr_card.murr_list, name='my_murrs'),
    path('create/', murr_card.murr_create, name='murr_create'),
    # murr_detail under construction: нужно переверстать старый шаблон с учетом новых инклюдови и апи вьъх
    path('murr_detail/<str:slug>', murr_card.murr_detail, name='murr_detail'),
    path('murr_detail/<str:slug>/update/', murr_card.murr_update, name='murr_update'),
    path('murr_detail/<str:slug>/delete/', murr_card.murr_delete, name='murr_delete'),
    path('comment_add/', murr_card.comment_add, name='comment_add'),
    path('comment_delete/', murr_card.comment_delete),
    path('comment_edit/', murr_card.comment_edit),
    path('comment_update/', murr_card.comment_update),
    path('murr_action/', murr_card.murr_action),
    path('search/', murr_card.search, name='search'),
]

murr/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Murren import views as murren
from .views import redirect_view, about

urlpatterns = [
    path('', redirect_view, name='redirect_view'),
    path('admin/', admin.site.urls),
    path('about/', about, name='about'),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('allauth.urls')),
    path('edit/', murren.murren_edit, name='edit'),
    path('murrs/', include('MurrCard.urls')),
    path('landing/', murren.landing, name='landing'),
    path('murren/', include('Murren.urls')),
    path('dashboard/', include('Dashboard.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MurrCard/models.py
from PIL import Image
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager
from tinymce import HTMLField
from uuslug import slugify

User = get_user_model()


class Murr(models.Model):

    CATEGORIES = [

        ('programming', '#программирование'),
        ('games', '#игры'),
        ('humor', '#смешное'),
        ('scince', '#наука'),
        ('sport', '#спорт'),
        ('cinema', '#кино'),
        ('music', '#музыка'),
        ('travels', '#путешествия'),
        ('relations', '#отношения'),
        ('etc', '#другое'),
    ]

    title = models.CharField(max_length=78, verbose_name='Заголовок', help_text="Максимум 78 символов")
    description = models.CharField(max_length=158, blank=True, verbose_name='Описание', help_text="Максимум 158 символа")
    content = HTMLField('Content')
    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='murrs')
    categories = models.CharField(max_length=20, verbose_name='Категория', choices=CATEGORIES)
    featured = models.BooleanField(default=True)
    cover = models.ImageField(blank=True, upload_to='murren_pics')
    tags = TaggableManager(blank=True, verbose_name='Теги', help_text="Список тегов через запятую. Максимум 40 символов")
    slug = models.CharField(verbose_name='Слаг для мурра', max_length=100, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('murr_detail', kwargs={'pk': self.id})

    def get_update_url(self):
        return reverse('murr_update', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('murr_delete', kwargs={'pk': self.id})

    @property
    def get_comments(self):
        return self.comments.order_by('-timestamp')

    @property
    def comment_count(self):
        return Comment.objects.filter(murr=self).count()

    @property
    def cover_url(self):
        if self.cover and hasattr(self.cover, 'url'):
            return self.cover.url

    def get_liked_murrens(self):
        return self.liked.values_list('murren_id', flat=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.cover:
            img = Image.open(self.cover.path)

            if img:
                output_size = (1000, 1000)
                img.thumbnail(output_size)
                img.convert('RGB').save(self.cover.path, "JPEG")

        self.slug = f'{slugify(self.title)}-{self.pk}'
        super(Murr, self).save()


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    murr = models.ForeignKey(Murr, related_name='comments', on_delete=models.CASCADE)
    reply = models.ForeignKey(
        "self",
        verbose_name="Коммент",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='children',
    )

    def __str__(self):
        return f'<Comment: {self.murr.title}>'


class Like(models.Model):
    murren = models.ForeignKey(User, related_name='likes', on_delete=models.CASCADE)
    murr = models.ForeignKey(Murr, related_name='liked', on_delete=models.CASCADE)

    class Meta:
        unique_together = ('murren', 'murr')

    def __str__(self):
        return f'{self.murren} liked {self.murr}'


class MurrAction(models.Model):
    REPORT = 'report'
    HIDE = 'hide'

    _ACTIONS_LIST = (
        (REPORT, 'Report Action'),
        (HIDE, 'Hide Action'),
    )

    kind = models.TextField(
        choices=_ACTIONS_LIST
    )
    murren = models.ForeignKey(
        User, models.CASCADE
    )
    timestamp = models.DateTimeField(
        auto_now_add=True
    )
    murr = models.ForeignKey(
        Murr,
        related_name='actions',
        on_delete=models.CASCADE
    )

    class Meta:
        unique_together = ('murren', 'murr', 'kind', )

MurrCard/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db.models import Q, Count
from django.http import JsonResponse, HttpResponseForbidden, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.views.decorators.http import require_POST
from taggit.models import Tag

from .forms import CommentForm, MurrForm
from .likes import LikeProcessor
from .actions import ActionProcessor
from .models import Murr, Comment, MurrAction
from murr.shortcuts import MurrenganPaginator


User = get_user_model()


def murr_list(request, **kwargs):
    """
    Output all murrs or murrs that filtered by tag
    or murrs queryset from kwargs
    """
    murrs = Murr.objects.all().annotate(report_count=Count('actions__kind',
                                                           filter=Q(actions__kind=MurrAction.REPORT)
                                                           )).exclude(report_count__gte=5)
    if not request.user.is_anonymous:
        actions = [MurrAction.REPORT, MurrAction.HIDE]
        murrs = murrs.exclude(actions__murren=request.user, actions__kind__in=actions)

    tag_name = kwargs.get('tag_name')
    if tag_name:
        tag = get_object_or_404(Tag, name=tag_name)
        murrs = murrs.filter(tags__name=tag)

    category = kwargs.get('category')
    if category:
        murrs = murrs.filter(categories=category)

    my_likes = kwargs.get('likes')
    if my_likes:
        murrens_likes = request.user.get_liked_murrs()
        murrs = Murr.objects.filter(liked__murr_id__in=murrens_likes)

    my_murrs = kwargs.get('my_murrs')
    if my_murrs:
        murrs = Murr.objects.filter(author=request.user)

    murrs = murrs.annotate(comments_total=Count('comments__pk'))
    murrs = murrs.order_by('-timestamp')
    page = request.GET.get('page', 1)
    paginator = MurrenganPaginator(murrs.distinct(), 10)
    page = paginator.page(page)
    context = {
        'page': page,
    }
    return render(request, 'MurrCard/murr_list.html', context)


def search(request):
    """ Filter murrs by search query and pass queryser to murr_list view """
    murrs = Murr.objects.all().annotate(report_count=Count('actions__kind',
                                                           filter=Q(actions__kind=MurrAction.REPORT)
                                                           )).exclude(report_count__gte=5)
    if not request.user.is_anonymous:
        actions = [MurrAction.REPORT, MurrAction.HIDE]
        murrs = murrs.exclude(actions__murren=request.user, actions__kind__in=actions)
    query = request.GET.get('q')
    if query:
        query_in_title = Q(title__icontains=query)
        query_in_desc = Q(description__icontains=query)
        query_in_tag = Q(tags__name__icontains=query)
        murrs = murrs.filter(query_in_title | query_in_tag | query_in_desc)
        if murrs.exists() is False:
            messages.add_message(request, messages.INFO, 'Поиск принес только опыт и 0 информации')

    murrs = murrs.annotate(comments_total=Count('comments__pk'))
    murrs = murrs.order_by('-timestamp')
    page = request.GET.get('page', 1)
    paginator = MurrenganPaginator(murrs.distinct(), 10)
    page = paginator.get_page(page)

    context = {
        'page': page,
        'search_query': f'q={query}&',
    }
    return render(request, 'MurrCard/murr_list.html', context)


def murr_detail(request, slug):
    """ Show single murr """
    murr = get_object_or_404(Murr, slug=slug)
    form = CommentForm()
    context = {'murr': murr, 'comment_form': form}

    try:
        # TODO when unauthorized user opens murr_detail page, take AttributeError
        murren = murr.author
        client = request.user
        following = client.masters.filter(master_id=murren.pk)
        already_follow = following.exists()
        context.update({
                   'murren': murren,
                   'already_follow': already_follow})
    except AttributeError:
        pass

    if request.method == 'POST':

        html = render_to_string('MurrCard/includes/_murr-detail_drawer_view.html', context, request)
        return JsonResponse({'html': html})
    context.update({'show_follow': True})
    return render(request, 'MurrCard/murr_detail.html', context)


@login_required
def murr_create(request):
    title = 'Создай'
    form = MurrForm(request.POST or None, request.FILES or None)
    author = request.user
    if request.method == 'POST' and form.is_valid():
        form.instance.author = author
        form.save()
        return redirect(reverse('murr_detail', kwargs={
            'slug': form.instance.slug
        }))

    context = {'title': title, 'form': form}
    return render(request, 'MurrCard/murr_create.html', context)


def murr_update(request, slug):
    template = 'MurrCard/murr_create.html'
    title = 'Измени'
    author = request.user
    murr = get_object_or_404(Murr, slug=slug, author=author)
    form = MurrForm(
        request.POST or None,
        request.FILES or None,
        instance=murr)
    if request.method == 'POST' and form.is_valid():
        form.instance.author = author
        form.save()
        return redirect(reverse('murr_detail', kwargs={
            'slug': form.instance.slug
        }))

    context = {'title': title, 'form': form}
    return render(request, template, context)


@login_required(login_url='/accounts/login')
def murr_delete(request, slug):
    if request.user.is_authenticated:
        user = request.user
        murr = get_object_or_404(Murr, slug=slug, author=user)
        murr.delete()
        return redirect(reverse('murr_list'))
    else:
        return HttpResponseForbidden()


@require_POST
@login_required
def comment_add(request):
    form = CommentForm(request.POST)
    # if not form.is_valid():
    #     return None

    murr_slug = request.POST.get('murr_slug')
    murr = get_object_or_404(Murr, slug=murr_slug)
    form.instance.user = request.user
    form.instance.murr = murr
    form.save()
    template = 'MurrCard/includes/_murr-detail_drawer_comments.html'
    comments = render_to_string(template, {'murr': murr}, request)
    return JsonResponse({'comments': comments})


@require_POST
@login_required
def comment_delete(request):
    author = request.user
    pk = request.POST.get('pk')
    comment = get_object_or_404(Comment, pk=pk, user=author)
    comment.delete()
    return JsonResponse({'ok': True})


def save_comment(request, pk, slug, template):
    data = dict()
    # murr = get_object_or_404(Murr, slug=slug)
    # comment = get_object_or_404(murr.get_comments, pk=pk)
    comment = get_object_or_404(Comment, pk=pk)
    if request.is_ajax():
        if request.method == 'POST':
            form = CommentForm(request.POST, instance=comment)
            if form.is_valid():
                form.save()
                data['success'] = True
                data['message'] = 'form inplace saved'
                data['content'] = render_to_string(template, context={'comment': comment}, request=request)
            else:
                data['success'] = False
                data['message'] = 'form is not valid'
            # print(f"{form.cleaned_data['content']}\n\t ==== were saved ====\ncontext:\n\t{context}\n")
        elif request.method == 'GET':
            print(request.GET)
            form = CommentForm(instance=comment)
            data['message'] = 'form inplace send'
            data['success'] = True
            data['html_form'] = render_to_string(template, context={'form': form}, request=request)
    else:
        raise Http404

    return JsonResponse(data)


@require_POST
@login_required
def comment_edit(request):
    author = request.user
    pk = request.POST.get('pk')
    comment = get_object_or_404(Comment, pk=pk, user=author)
    form = CommentForm(request.POST, instance=comment, auto_id='comment-edit-%s')
    if form.is_valid():
        context = {'edit_form': form}
        html = render_to_string('MurrCard/includes/_comment_edit_form.html', context, request)
        return JsonResponse({'html': html})
    return JsonResponse({'ok': True})


@require_POST
@login_required
def comment_update(request):
    author = request.user
    pk = request.POST.get('pk')
    comment = get_object_or_404(Comment, pk=pk, user=author)
    form = CommentForm(request.POST, instance=comment)
    if form.is_valid():
        form.save()
        murr_slug = request.POST.get('murr_slug')
        murr = get_object_or_404(Murr, slug=murr_slug)
        template = 'MurrCard/includes/_murr-detail_drawer_comments.html'
        comments = render_to_string(template, {'murr': murr}, request)
        return JsonResponse({'comments': comments})


@login_required()
def like(request):
    if request.method == 'GET':
        raise Http404

    raw_data = request.POST.dict()
    processor = LikeProcessor(raw_data)
    processor.process()
    if processor.errors:
        return JsonResponse({'error': processor.errors})

    processor.save()
    murr = request.POST.get('murr')
    likes = Murr.objects.get(slug=murr).liked.count() or ''
    return JsonResponse({'ok': True, 'likes': likes})


@login_required()
def unlike(request):
    if request.method == 'GET':
        raise Http404

    raw_data = request.POST.dict()
    processor = LikeProcessor(raw_data)
    processor.process()
    if processor.errors:
        return JsonResponse({'error': processor.errors})

    processor.delete()
    murr = request.POST.get('murr')
    likes = Murr.objects.get(slug=murr).liked.count() or ''
    return JsonResponse({'ok': True, 'likes': likes})


@require_POST
@login_required
def murr_action(request):
    raw_data = request.POST.dict()
    processor = ActionProcessor(raw_data)
    processor.process()
    if processor.errors:
        return JsonResponse({'error': processor.errors})

templates/MurrCard/base_murrs.html
{% extends 'base.html' %}

templates/MurrCard/landing.html
<!DOCTYPE html>

{% load static %}

<head>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/landing.css">

    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}">

    <title>Murrengan</title>

</head>

<body>


<nav class="navbar navbar-expand-sm navbar-light sticky-top bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'murr_list' %}">
            <img src="{% static 'img/favicon.ico' %}" width="30" height="30" class="d-inline-block align-top">
            Murrengan
        </a>

        <button class="navbar-toggler" data-toggle="collapse" data-target="#base_navbar">

            <span class="navbar-toggler-icon"></span>

        </button>

        <div class="collapse navbar-collapse" id="base_navbar">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="#Start" class="nav-link active text-center">О нас</a>
                </li>
                <li class="nav-item">
                    <a href="#About" class="nav-link text-center">Как работает?</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'murr_list' %}" class="nav-link text-center">Все Мурры</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'account_signup' %}" class="nav-link text-center">Регистрация</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<section id="showcase" class="d-flex justify-content-center align-items-center">
    <div id="overlay"></div>
    <div id="header" class="container text-white text-center">
        <h1 class="display-4">Murrengan</h1>
        <p class="lead">Создай команду или присоединись к существующей</p>
        <button id="#About" class="btn btn-lg btn-info px-5 mt-2" data-toggle="modal" data-target="#bokingModel">
            Куда я попал?
        </button>
        <button id="" class="btn btn-lg btn-danger px-5 mt-2" data-toggle="modal" data-target="#bokingModel">
            Регистрация!
        </button>
    </div>
</section>

<section id="Start">
    <div class="container text-center">
        <h2 id="in_a_team">В команде единомышленников<br> добьешься большего,<br> чем в одиночку!</h2>

        <div class="p-3 mt-4">
            <img src="{% static "/img/wolf.svg" %}" width="200" height="200" class="img-fluid">
            <p class="lead font-weight-bolder mt-3">Одинокий волк погибает,<br> но стая живёт.</p>
        </div>

    </div>
</section>


<section id="About" class="">
    <div class="container text-center">
        <h2>Murrengan - это группа людей, объединенная для достижения цели.</h2>
    </div>
</section>


<section id="Master" class="d-flex justify-content-center align-items-center">
    <div id="overlay"></div>
    <div id="header" class="container text-black text-left">
        <h1 class="display-4 ">Мастер</h1>
        <p class="lead font-weight-normal">Лидер команды по постижению цели</p>

        <button id="where_i_am" class="btn btn-lg btn-info mt-2" data-toggle="modal" data-target="#bokingModel">
            Стать Мастером!
        </button>
    </div>
</section>


<section id="Murren" class="d-flex justify-content-center align-items-center">
    <div id="overlay"></div>
    <div id="header" class="container text-white text-right">
        <h1 class="display-4 ">Муррен</h1>
        <p class="lead font-weight-normal">Участник команды по постижению цели</p>

        <button id="where_i_am" class="btn btn-lg btn-info mt-2" data-toggle="modal" data-target="#bokingModel">
            Стать Мурреном!
        </button>
    </div>
</section>

<section id="footer" class="bg-secondary py-1">
    <ul class="nav text-center justify-content-center flex-column flex-sm-row">
        <li class="nav-item">
            <a href="" class="nav-link text-white">Murr</a>
        </li>
        <li class="nav-item">
            <a href="" class="nav-link text-white">Murr</a>
        </li>
        <li class="nav-item">
            <a href="" class="nav-link text-white">Благодарю за посещение сайта =)</a>
        </li>
        <li class="nav-item">
            <a href="" class="nav-link text-white">Murr</a>
        </li>
        <li class="nav-item">
            <a href="" class="nav-link text-white">Murr</a>
        </li>
    </ul>

</section>


</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="/static/js/custom.js"></script>

</html>

templates/MurrCard/murr_create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block css  %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static "css/murr_create.css" %}" />
{% endblock %}

{% block content %}

  <div class="container text-center col-md-6 col-sm-12">
    <h3 class="text-center">{{ title }} свой Мурр!</h3>
{# для добавление tinymce добавить {{ form.media }} and enctype="multipart/form-data"#}
    {{ form.media }}
    <form method="POST" enctype="multipart/form-data" id="target">
      {% crispy form %}
    </form>
  </div>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        });

        $( "#target" ).submit(function( event ) {
            {#alert( "Handler for .submit() called." );#}
            event.preventDefault();
        });

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#cover-img').attr('src', e.target.result);
                    $(this).off('submit').submit();
                }

                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#id_cover").change(function(){
            readURL(this);
        });

        $("input[type='image']").click(function () {
            $("input[id='id_cover']").click();
            console.log($("input[id='id_cover']").val())
        });

        $( "#submit-id-submit" ).on('click', function() {
            {#$( "#target" ).submit();#}
            console.log(this);
            $('#target').off('submit').submit();
        });
    </script>
{% endblock js %}

templates/MurrCard/murr_detail.html
{% extends 'MurrCard/base_murrs.html' %}
{% load static %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static "css/murr_detail.css" %}" />
    <link rel="stylesheet" href="{% static "css/emojionearea.min.css" %}" />
    <link rel="stylesheet" href="{% static "css/media-object.css" %}" />
{% endblock css %}


{% block title %}{{ murr.title }}{% endblock %}

{% block content %}
    <div class="container col-7 card murr_detail_container">
    {% include 'MurrCard/includes/_murr-detail_drawer_view.html' %}
    </div>
{% endblock content %}

{% block js %}
    {{ block.super }}
    <script src="{% static "js/emojionearea.min.js" %}"></script>
    <script src="{% static "js/custom.js" %}"></script>
    <script src="{% static "js/bootstrap-dialog.min.js" %}"></script>
    <script src="{% static "js/murr_detail.js" %}"></script>
    <script>$('.js-murr-detail').murrDetail();</script>
    <script src="{% static "js/profile.js" %}"></script>
    <script> $('.profile').murrenProfile(); </script>
{% endblock js %}

templates/MurrCard/murr_list.html
{% extends 'MurrCard/base_murrs.html' %}
{% load static %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
    <link rel="stylesheet" href="{% static "css/emojionearea.min.css" %}" />
    <link rel="stylesheet" href="{% static "css/masonry.css" %}" />
    <link rel="stylesheet" href="{% static "css/murr_card.css" %}" />
    <link rel="stylesheet" href="{% static "css/murr-detail_drawer.css" %}" />
    <link rel="stylesheet" href="{% static "css/murr_detail.css" %}" />
{% endblock css %}

{% block content %}
    <div class="container py-1">
        <div class="murr-list masonry" data-csrf_token="{{ csrf_token }}" data-murren="{{ request.user.pk|default_if_none:'' }}">
            {% for murr in page %}
                {% include 'MurrCard/includes/_murr_list_card.html' %}
            {% endfor %}
        </div>
    </div>
    <div class="loading" style="display: none;">
      Loading...
    </div>

  {% if page.has_next %}
    <a class="infinite-more-link" href="?page={{ page.next_page_number }}">More</a>
  {% endif %}

    {% include 'MurrCard/includes/_murr-detail_drawer.html' %}
{% endblock content %}

{% block js %}
    {{ block.super }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/shortcuts/infinite.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.1/imagesloaded.pkgd.min.js"></script>
    <script src="{% static "js/emojionearea.min.js" %}"></script>
    <script src="{% static "js/murr_detail.js" %}"></script>
    <script src="{% static "js/murr_list.js" %}"></script>
    <script src="{% static "js/masonry.js" %}"></script>
    <script>$('.murr-list').murrList();</script>
{% endblock js %}